=== kang-de-conqueror/prx301_assignment/src/main/webapp/xsd/User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringType">
    <xs:restriction base="xs:string" />
</xs:simpleType>
<xs:simpleType name="intType">
  <xs:restriction base="xs:nonNegativeInteger"/>
</xs:simpleType>
<xs:simpleType name="IdType">
    <xs:restriction base="xs:ID">
        <xs:pattern value="A[0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="Gender">
    <xs:restriction base="xs:string">
        <xs:enumeration value="male"/>
        <xs:enumeration value="female"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="Role">
    <xs:restriction base="xs:integer">
        <xs:enumeration value="1"/>
        <xs:enumeration value="0"/>
    </xs:restriction>
</xs:simpleType>

<xs:attribute name="UserId" type="IdType"/>
<xs:element name="Username" type="stringType"/>
<xs:element name="Password" type="stringType"/>
<xs:element name="Name" type="stringType"/>
<xs:element name="Gender" type="Gender"/>
<xs:element name="Age" type="intType"/>
<xs:element name="NumberPhone" type="intType"/>
<xs:element name="Address" type="stringType"/>
<xs:element name="Role" type="Role"/>


    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Username"/>
                <xs:element ref="Password"/>
                <xs:element ref="Name"/>
                <xs:element ref="Gender"/>
                <xs:element ref="Age"/>
                <xs:element ref="NumberPhone"/>
                <xs:element ref="Address"/>
                <xs:element ref="Role"/>
            </xs:sequence>
            <xs:attribute ref="UserId" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="User" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kang-de-conqueror/prx301_assignment/src/main/webapp/xml/User.xml
<?xml version="1.0" encoding="UTF-8"?>

<Users
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="User.xsd">
<User UserId="A123">
    <Username>khanh</Username>
    <Password>khanh</Password>
    <Name>sss</Name>
    <Gender>male</Gender>
    <Age>122</Age>
    <NumberPhone>02923783</NumberPhone>
    <Address>hcm</Address>
    <Role>Cus</Role>
</User>
<User UserId="A124">
    <Username>khanh</Username>
    <Password>khanh</Password>
    <Name>sss</Name>
    <Gender>female</Gender>
    <Age>122</Age>
    <NumberPhone>02923783</NumberPhone>
    <Address>hcm</Address>
    <Role>Emp</Role>
</User>
</Users>

=== kang-de-conqueror/prx301_assignment/src/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="User.xsd">
    <User>
        <UserId>A000</UserId>
        <Username>admin</Username>
        <Password>123</Password>
        <Gender>male</Gender>
        <Age>1</Age>
        <NumberPhone>02923783152</NumberPhone>
        <Address>hcm</Address>
        <Role>0</Role>
    </User>
    <User>
        <UserId>A001</UserId>
        <Username>cus</Username>
        <Password>123</Password>
        <Gender>male</Gender>
        <Age>12</Age>
        <NumberPhone>02923783152</NumberPhone>
        <Address>hcm</Address>
        <Role>1</Role>
    </User>

</Users>
